import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { PrismicRichText } from '@prismicio/react';
import { fetchFromPrismic } from '../api/prismic';
import { asText } from '@prismicio/helpers';

type PrismicRichText = any;

type Props = any;

const Home: NextPage = ({home, pageLinks}: Props) => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Verkefni 6</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <PrismicRichText field={home[0].node.title} />
        <PrismicRichText field={home[0].node.intro} />
        <Image 
          src={home[0].node.mynd.url}
          width={home[0].node.mynd.dimensions.width/4}
          height={home[0].node.mynd.dimensions.height/4}
          alt={home[0].node.mynd.alt} 
        />
        <div className={styles.grid}>

        {pageLinks.map(function(link: any, i: any){
          return(
            <Link href={'/'+link.node._meta.uid}>
              <a>{link.node.title[0].text}</a>
            </Link>
            )
        })}

        </div>
      </main>

    </div>
  )
}

const query = `
  query{
    allHomes{
      edges{
        node{
          title
          intro
          mynd
          _meta {
            id
          }
          _linkType
          
        }
      }
    }
    allPages{
      edges{
        node{
          title
          _meta{
            uid
          }
        }
      }
    }
  }
`;

type PrismicResponse = {
  allHomes?: {
    edges?: Array<{
      node?: {
        title?: Array<{
          type?: string,
          text?: string
        }>
        intro?: Array<{
          type?: string,
          text?: PrismicRichText
        }>
        mynd?: {
          dimension?:{
            width?: number,
            height?: number
          }
          alt?: string,
          copyrigt?: string,
          url?: string
        }
        _meta?: {
          id?: string
        }
      }
    }>;
  }
  allPages?:{
    edges?: Array<{
      node?: {
        title?: Array<{
          type?: string,
          text?: string,
          spans?: []
        }>
        _meta?:{
          uid?: string
        }
      }
    }>
  }
}

export async function getServerSideProps() {
  const result = await fetchFromPrismic<PrismicResponse>(query);
  const home = result.allHomes?.edges;
  const pageLinks = result.allPages?.edges;
  return {
    props: { home, pageLinks },
  };
}

export default Home
